-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: 616c1ebd1898c91de9a0548866a59cbd9f4547f6
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: debug-statements
        language_version: python2.7
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: flake8
        language_version: python2.7
-   repo: git@github.com:asottile/reorder_python_imports
    sha: 3d86483455ab5bd06cc1069fdd5ac57be5463f10
    hooks:
    -   id: reorder-python-imports
        language_version: python2.7
