-   repo: git@github.com:pre-commit/pre-commit-hooks
    sha: b08f834d65fed15e25cbe3073df7ff457459801a
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: ^test_data/
    -   id: autopep8-wrapper
        args: ['-i', '--ignore=E265,E309,E501']
        exclude: ^test_data/
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: flake8
        exclude: ^test_data/
-   repo: git@github.com:pre-commit/pre-commit
    sha: 645838cb514583249478e347aa80a0af743edace
    hooks:
    -   id: validate_config
    -   id: validate_manifest
-   repo: git@github.com:asottile/reorder_python_imports
    sha: ea9fa14a757bb210d849de5af8f8ba2c9744027a
    hooks:
    -   id: reorder-python-imports
        exclude: ^test_data/
